apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  labels:
    app: todo
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      tier: api
  template:
    metadata:
      labels:
        app: todo
        tier: api
    spec:
      containers:
      - name: todo-api
        image: todo-api:latest
        imagePullPolicy: Never  # Pour les images locales
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: todouser
        - name: DB_PASSWORD
          value: todopassword
        - name: DB_NAME
          value: tododb
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  labels:
    app: todo
    tier: api
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: todo
    tier: api