apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  labels:
    app: todo
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Port accessible depuis l'extérieur (entre 30000-32767)
  selector:
    app: todo
    tier: frontend