apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: todo
    tier: backend
spec:
  selector:
    matchLabels:
      app: todo
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo
        tier: backend
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_DATABASE
          value: tododb
        - name: MYSQL_USER
          value: todouser
        - name: MYSQL_PASSWORD
          value: todopassword
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS tododb;
    USE tododb;

    CREATE TABLE IF NOT EXISTS tasks (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        completed BOOLEAN DEFAULT false,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO tasks (title) VALUES 
    ('Apprendre Docker'),
    ('Configurer Kubernetes'),
    ('Tester les volumes persistants');